services:
  sample_python_project:
    build: .
    container_name: sample_python_project
    # user: "1000:1000"
    mem_reservation: 256m
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          # cpus: "1.0"
          memory: 512m
        reservations:
          memory: 256m
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    # read_only: true
    cap_drop:
      - ALL
